server:
  port: 8080
  mode: debug

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: password
    dbname: taskmanager
    sslmode: disable
  
  mongodb:
    uri: mongodb://localhost:27017
    database: taskmanager

jwt:
  secret: your-secret-key
  expires_in: 24h
