server:
  port: 8080
  mode: debug

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: password
    dbname: taskmanager
    sslmode: disable

jwt:
  secret: your-secret-key-please-change-in-production
  expires_in: 24h
